// Objective-C API for talking to github.com/Dreamacro/clash/lib Go package.
//   gobind -lang=objc github.com/Dreamacro/clash/lib
//
// File is generated by gobind. Do not edit.

#ifndef __Clash_H__
#define __Clash_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol ClashClient;
@class ClashClient;

@protocol ClashClient <NSObject>
- (void)onLog:(NSString* _Nullable)level payload:(NSString* _Nullable)payload;
- (void)onTraffic:(int64_t)up down:(int64_t)down;
@end

FOUNDATION_EXPORT void ClashCloseAllConnections(void);

FOUNDATION_EXPORT void ClashCloseConnection(NSString* _Nullable id_);

FOUNDATION_EXPORT NSData* _Nullable ClashGetProxies(void);

FOUNDATION_EXPORT void ClashHealthCheck(NSString* _Nullable name);

FOUNDATION_EXPORT BOOL ClashRun(NSString* _Nullable home, NSString* _Nullable config, id<ClashClient> _Nullable c, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL ClashSetConfig(NSString* _Nullable uuid, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void ClashSetLogLevel(NSString* _Nullable level);

FOUNDATION_EXPORT void ClashSetSelect(NSString* _Nullable provider, NSString* _Nullable proxy);

FOUNDATION_EXPORT void ClashSetTunnelMode(NSString* _Nullable mode);

FOUNDATION_EXPORT NSData* _Nullable ClashSnapshot(void);

@class ClashClient;

@interface ClashClient : NSObject <goSeqRefInterface, ClashClient> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onLog:(NSString* _Nullable)level payload:(NSString* _Nullable)payload;
- (void)onTraffic:(int64_t)up down:(int64_t)down;
@end

#endif
